// Code generated by ogen, DO NOT EDIT.

package api

import (
	"net/http"

	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
	"github.com/ogen-go/ogen/validate"
)

// InfoGetParams is parameters of GET /info operation.
type InfoGetParams struct {
	Group string
	Song  string
}

func unpackInfoGetParams(packed middleware.Parameters) (params InfoGetParams) {
	{
		key := middleware.ParameterKey{
			Name: "group",
			In:   "query",
		}
		params.Group = packed[key].(string)
	}
	{
		key := middleware.ParameterKey{
			Name: "song",
			In:   "query",
		}
		params.Song = packed[key].(string)
	}
	return params
}

func decodeInfoGetParams(args [0]string, argsEscaped bool, r *http.Request) (params InfoGetParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode query: group.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "group",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.Group = c
				return nil
			}); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "group",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: song.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "song",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.Song = c
				return nil
			}); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "song",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}
